
title: Portfolio
name: Pablo Reina
description: Conecto informaci√≥n para ayudar a crear conocimiento
home: /assets/img/home.png
logo: /assets/img/logo.jpg
show_downloads: false
show_menu: true
google_analytics: 
theme: jekyll-theme-minimal