
title: Pablo Reina
description: Data Scientist and SW Developer
logo: [https://avatars0.githubusercontent.com/u/15930285?s=460&u=3398c576d1b005b9d9ed83684031e6db582fb4d4&v=4]
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal